IngSoftware/urls.py
from django.contrib import admin
from django.urls import path
from AppSoft import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', views.login, name='login'),
    path('registro/', views.crearcuenta, name='register'),
    path('comprasVer/',views.compras_Ver,name= 'comprasVer'),
    path('comprasAgregar/<str:nombre>',views.compra_agregar,name='comprasAgregar'),
    path('agregarCompraBodeguero/<str:nombre>', views.compra_agregarBodeguero, name='compra_agregarBodeguero'),
    
    
    path('materiaVer/',views.materiaVer, name='materiaVer'),
    path('materiaCrear/',views.materiaCrear,name='materiaCrear'),
    path('materiaActualizar/<int:id>',views.materiaActualizar,name='materiaActualizar'),
    path('materiaDeshabilitar/<int:id>',views.materiaDeshabilitar,name='materiaDeshabilitar'),
    path('materiasDeshabilitadas/',views.materiasDeshabilitadas,name='materiasDeshabilitadas'),
    path('materiasHabilitar/<int:id>',views.materiaHabilitar,name='materiasHabilitar'),
    
    

    
    path('productosVer/', views.productosVer, name='productosVer'), 
    path('nuevosProducto/', views.productosCrearNuevo,name='productosCrearNuevo'),
    path('productosActualizar/<int:id>', views.productosActualizar,name='productosActualizar'),
    path('productosDeshabilitar/<int:id>', views.productosDeshabilitar,name='productosDeshabilitar'),
    path('productosDeshabilitados/',views.productosVerDeshabilitados,name='productosDeshabilitados'),
    path('productosHabilitar/<int:id>',views.productosHabilitar,name='productosHabilitar'),
   
   
    path('proveedoresVer/', views.proveedoresVer, name='proveedoresVer'),
    path('proveedoresCrear/', views.proveedoresCrear, name='proveedoresCrear'),
    path('proveedoresActualizar/<int:id>', views.proveedoresActualizar, name='proveedoresActualizar'),
    path('proveedoresDeshabilitar/<int:id>',views.proveedoresDeshabilitar, name='proveedoresDeshabilitar'),
    path('proveedoresDeshabilitados/',views.proveedoresDeshabilitados, name='proveedoresDeshabilitados'),
    path('proveedoresHabilitar/<int:id>',views.proveedoresHabilitar, name='proveedoresHabilitar'),
    path('delete_proveedores/<int:id>/', views.delete_proveedores, name='delete_proveedores'),
    
    
    path('lista_usuarios/', views.lista_usuarios,name='lista_usuarios'),
    path('crear_usuario/', views.crear_usuario,name='crear_usuario'),
    path('actualizar_usuario/<int:id>', views.actualizar_usuario,name='actualizar_usuario'),
    path('delete-usuario/<int:emp_id>/', views.delete_usuario, name='delete_usuario'),
    
    
    path('bodegueroVer/',views.bodeguerosVer,name='bodeguerosVer'),
    path('bodegueroCrear/',views.bodegueroCrear, name='bodegueroCrear'),
    path('materiaCrearBodeguero/', views.materiaCrearBodeguero, name='materiaCrearBodeguero'),
    path('materiaVerBodeguero/', views.materiaVerBodeguero, name='materiaVerBodeguero'),
    path('compras_bodeguero/<str:nombre>',views.compra_agregarBodeguero,name='agregarCompraBodeguero'),
    path('productos_bodeguero',views.productosVerBodeguero, name='verProductosBodeguero'),
    path('proveedores_bodeguero/',views.proveedoresVerBodeguero,name='verProveedoresBodeguero'),
    
    
]

AppSoft/models.py
from django.db import models
import datetime
from django.core.exceptions import ValidationError
from .validators import validar_rut_mod11,MinValueValidator


# Create your models here.
class MateriaPrima(models.Model):
    UNIDAD_MEDIDA = [
        ('kg', 'Kilogramo'),
        ('g', 'Gramo'),
        ('l', 'Litro'),
        ('ml', 'Mililitro'),
        # Agrega más opciones según tus necesidades
    ]
    
    nombre = models.CharField(max_length=60)
    cantidad = models.FloatField()
    unidadMedida= models.CharField(max_length=5,choices=UNIDAD_MEDIDA)
    estadoMateria = models.BooleanField(default=True)
    def __str__(self):
        return self.nombre

def validar_rut(rut):
    if not validar_rut_mod11(rut):
        raise ValidationError("El RUT ingresado no es válido.")

class Proveedores (models.Model):
    nombre = models.CharField(max_length=50)
    contacto = models.CharField(max_length=12)
    estado= models.BooleanField(default=True)
    rut = models.CharField(max_length=10, unique=True, validators=[validar_rut])

    def __str__(self):
        return f"{self.nombre} - {self.rut}"


    
class Productos(models.Model):
    nombre = models.CharField(max_length=60, unique=True)
    cantidad = models.IntegerField()
    composicion = models.ManyToManyField('MateriaPrima', through='ProductoMateria', related_name='productos')
    estadoProducto = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs) 



class ProductoMateria(models.Model):
    producto = models.ForeignKey(Productos, on_delete=models.CASCADE)
    materia = models.ForeignKey(MateriaPrima, on_delete=models.CASCADE)
    cantidad_utilizada = models.FloatField(default=0)  # Cantidad de esta materia prima necesaria para el producto

    def __str__(self):
        return f"{self.producto.nombre} - {self.materia.nombre} - {self.cantidad_utilizada}"



class Usuario (models.Model):
    nombre= models.CharField(max_length=60)
    contraseña = models.CharField(max_length=10)
    rol = models.CharField(max_length=30)
    estadoUsuario = models.CharField(max_length=25) #Lo arregle para que funcioné de mejor manera el estado y no tener que investigar más de la cuenta

class Compra(models.Model):
    fecha = models.DateField()
    proveedor = models.ForeignKey(Proveedores, on_delete=models.CASCADE)
    lote = models.DecimalField(max_digits=10, decimal_places=2)
    cantidad = models.FloatField(validators=[MinValueValidator(0.0)])
    materia = models.ForeignKey(MateriaPrima, on_delete=models.CASCADE, blank=True, null=True)
    
    def __str__(self):
        return f"Compra {self.id} - {self.materia.nombre}"
    

class Bodeguero (models.Model):
    nombre = models.CharField(max_length=50)
    contacto = models.CharField(max_length=16) 
    def __str__(self):
        return self.nombre

AppSoft/forms.py
from django import forms 
from django.forms import inlineformset_factory
from AppSoft.models import MateriaPrima,Proveedores,Productos,Usuario,Compra, Bodeguero

class MateriaPrimaForm(forms.ModelForm):
    class Meta:
        model = MateriaPrima
        fields='__all__'
        widgets={
            'nombre' : forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre de la materia','required': 'required'}),
            'unidadMedida': forms.Select(attrs={'class': 'form-select', 'required': 'required'})
        }

class Usuariocuentaform(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = ['nombre', 'rol','contraseña', 'estadoUsuario']
        widgets = {
            'nombre' : forms.TextInput(attrs={'class':'form-control','placeholder':'Nombre Usuario','required':'required'}),
            'rol' : forms.Select(attrs={'class':'form-control','placeholder':'Rol','required':'required'},choices={'administrador':'administrador','bodeguero':'bodeguero'}),
            'contraseña' : forms.TextInput(attrs={'class':'form-control','type':'password','placeholder':'contraseña','required':'required'}),
            'estadoUsuario' : forms.CheckboxInput(attrs={'class':'form-check-input'})
        }

    def clean_nombre(self):
        nombre= self.cleaned_data.get('nombre')
        if Usuario.objects.filter(nombre=nombre).exists():
             raise forms.ValidationError('utilize otro nombre')
        return nombre    
    
    def clean_tipo(self):
        rol = self.cleaned_data.get('rol')
        if rol not in ['administrador', 'bodeguero']:
            raise forms.ValidationError('Tipo de usuario inválido.')
        return rol       

class ProveedoresForm(forms.ModelForm):
    class Meta:
        model = Proveedores
        fields = '__all__'
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre del Proveedor'}),
            'contacto': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Contacto', 'min': 100000000, 'max': 99999999999, 'pattern': r'^\d{9}$'}),
            'rut': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'RUT', 'pattern': r'^\d{1,8}-[0-9kK]{1}$'})
        }

    def clean_nombre(self):
        nombre = self.cleaned_data.get('nombre')
        if Proveedores.objects.filter(nombre=nombre).exists():
            raise forms.ValidationError('Ya existe un proveedor con este nombre.')
        return nombre


class ProductosForm(forms.ModelForm):
    composicion = forms.ModelMultipleChoiceField(
        queryset=MateriaPrima.objects.filter(estadoMateria=True),  # Solo materias activas
        widget=forms.CheckboxSelectMultiple
    )
    cantidad = forms.IntegerField(
        min_value=1,
        label='Cantidad de Productos',
        widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Cantidad Producto', 'required': 'required'})
    )

    class Meta:
        model = Productos
        fields = ['nombre', 'cantidad', 'composicion']
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre Producto', 'required': 'required'}),
        }

    def clean(self):
        cleaned_data = super().clean()
        composicion = cleaned_data.get('composicion')
        cantidad = cleaned_data.get('cantidad')

        if composicion:
            for materia in composicion:
                if materia.cantidad < cantidad:
                    raise forms.ValidationError(f"No hay suficiente stock de la materia prima: {materia.nombre}. Disponible: {materia.cantidad}.")
        return cleaned_data




class ProductoMateriaForm(forms.Form):
    materia_id = forms.IntegerField(widget=forms.HiddenInput())
    cantidad_utilizada = forms.FloatField(label="Cantidad utilizada", min_value=1)


class CantidadMateriaPrimaForm(forms.Form):
    materia_id = forms.IntegerField(widget=forms.HiddenInput())
    cantidad_utilizada = forms.FloatField(label="Cantidad utilizada", min_value=0)



class UsuarioForm(forms.ModelForm):
    class Meta:
        model = Usuario
        fields='__all__'

class CompraForm(forms.ModelForm):
    class Meta:
        model = Compra
        fields = ['fecha', 'proveedor', 'lote', 'cantidad']  # Excluir 'materia' para no mostrarlo

        widgets = {
            'fecha': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
            'proveedor': forms.Select(attrs={'class': 'form-select', 'required': 'required'}),
            'lote': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Lote'}),
            'cantidad': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Cantidad'}),
        }

class BodegueroForm(forms.ModelForm):
    class Meta:
        model = Bodeguero
        fields='__all__'
        widgets = {
            'nombre' : forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre del Bodeguero'}),
            'contacto' : forms.TextInput(attrs= {'class':'form-control','placeholder' : 'Contacto' })

        }

templates/agregarCantidadProducto.html
{% include 'header.html' %}
<div class="container mt-5">
    <h1>{{ titulo }} - {{ producto.nombre }}</h1>

    {% if messages %}
        {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    {% endif %}


    <form method="post">
        {% csrf_token %}
        
        <div class="mb-3">
            <label for="nombre" class="form-label">Nombre del Producto</label>
            <input type="text" class="form-control" id="nombre" name="nombre" value="{{ producto.nombre }}" required>
        </div>
        
        <button type="submit" class="btn btn-primary">Actualizar Nombre</button>
    </form>
</div>
{% include 'footer.html' %}

templates/comprar_agregar.html
{%include 'header.html'%}
<div class="container mt-5">
  {% if messages %}
        {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    {% endif %}
  <div class="alert alert-primary display-1">{{titulo}}</div>
  <form method="POST" action="#">
    {% csrf_token %}
    <div class="mb-3">
      <label for="fecha" class="form-label">Fecha</label>
      {{ form.fecha }}
    </div>
    <div class="mb-3">
        {{ form.proveedor.label_tag }}
        {{ form.proveedor }}  
    </div>
    <div class="mb-3">
        <label for="orden" class="form-label">Orden de compra</label>
        <input type="text" class="form-control" id="orden" name="orden" required>
    </div>
    <div class="mb-3">
        <label>Materia:</label>
        <!-- Campo oculto para enviar el ID de la materia -->
        <input type="hidden" name="materia" value="{{ nomMateria.id }}">
        <input type="text" class="form-control" value="{{ nomMateria.nombre }}" readonly>
    </div>
    <div class="mb-3">
        <label for="id_lote" class="form-label">Lote</label>
        {{ form.lote }}
    </div>
    <div class="mb-3">
        <label for="id_cantidad" class="form-label">Cantidad</label>
        {{ form.cantidad }}
    </div>
    <div class="mt-4">
        <button type="submit" class="btn btn-primary">Agregar</button>
    </div>
  </form>
  <div class="mb-3">
  <a href="{%url 'materiaVer'%}" class="btn btn-primary">volver</a>
</div>
</div>
{%include 'footer.html'%}

templates/compras_bodeguero.html
{%include 'header_bodeguero.html'%}
<div class="container mt-5">
  <div class="alert alert-primary display-1">{{titulo}}</div>
  <form method="POST" action="#">
    {% csrf_token %}
    <div class="mb-3">
      <label for="fecha" class="form-label">Fecha</label>
      {{ form.fecha }}
    </div>
    <div class="mb-3">
        {{ form.proveedor.label_tag }}
        {{ form.proveedor }}  
    </div>
    <div class="mb-3">
        <label for="orden" class="form-label">Orden de compra</label>
        <input type="text" class="form-control" id="orden" name="orden" value="{{ next_id }}" readonly required>
    </div>
    <div class="mb-3">
        <label>Materia:</label>
        <!-- Campo oculto para enviar el ID de la materia -->
        <input type="hidden" name="materia" value="{{ nomMateria.id }}">
        <input type="text" class="form-control" value="{{ nomMateria.nombre }}" readonly>
    </div>
    <div class="mb-3">
        <label for="id_precio" class="form-label">Lote</label>
        {{ form.lote }}
    </div>
    <div class="mb-3">
        <label for="id_cantidad" class="form-label">Cantidad</label>
        {{ form.cantidad }}
    </div>
    <div class="mt-4">
        <button type="submit" class="btn btn-primary">Agregar</button>
    </div>
  </form>
  <div>
  <a href="{%url 'materiaVerBodeguero'%}" class="btn btn-primary">volver</a>
</div>
</div>
{%include 'footer.html'%}

templates/compras_ver.html
{%include 'header.html'%}
<div class="container mt-5">
<div class="alert alert-primary display-1">{{titulo}}</div>
<div class="mb-3">
    <form method="GET" class="row g-3 mb-4">
        <div class="row align-items-center">
            <div class="col-md-10 d-flex align-items-center gap-3">
                <div class="d-flex align-items-center me-3">
                    <label for="fecha_inicio" class="form-label me-2">Fecha Inicio</label>
                    <input type="date" id="fecha_inicio" name="fecha_inicio" class="form-control">
                </div>
                <div class="d-flex align-items-center me-3">
                    <label for="fecha_fin" class="form-label me-2">Fecha Fin</label>
                    <input type="date" id="fecha_fin" name="fecha_fin" class="form-control">
                </div>
                <button type="submit" class="btn btn-primary"><i class="bi bi-search"></i> Filtrar</button>
            </div>
        </div>
        
            
    </form>
</div>
{%if compras%}
         <table class="table table-striped">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>fecha</th>
                    
                    <th>lote</th>
                    <th>cantidad</th>
                    <th>Materia prima</th>
                    <th>Proveedor</th>
                    
                </tr>
            </thead>
            <tbody>
                {%for mat in compras%}
                <tr>
                    <td>{{mat.id}}</td>
                    <td>{{mat.fecha}}</td>
                    
                    <td>{{mat.lote}}</td>
                    <td>{{mat.cantidad}}</td>
                    <td>{{mat.materia.nombre}}</td>
                    <td>{{mat.proveedor.nombre}}</td>
                
                   
                   
                </tr>
                {%endfor%}
            </tbody>
         </table>
        {%else%}
            <div class="alert alert-info">No Hay Compras!!!!</div>
        {%endif%}
</div>

{%include 'footer.html'%}

templates/footer.html
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</html>

templates/header.html
{%load static%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
    
    
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <ul class="nav nav-underline">
            <li class="nav-item">
                <a class="nav-link" href="{%url 'proveedoresVer'%}">Proveedores</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" aria-current="page" href="{%url 'materiaVer'%}">Materia</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{%url 'productosVer'%}">Productos</a>
            </li>
            
            <li class="nav-item">
                <a class="nav-link"href="{%url 'lista_usuarios'%}">Usuarios</a>
            </li>
            <li class="nav-item">
                <a class="nav-link"href="{%url 'bodeguerosVer'%}">Bodegueros</a>
            </li>
            <li class="nav-item">
                <a class="nav-link"href="{%url 'comprasVer'%}">Ingresos</a>
            </li>
            <li class="nav-item">
                <a class="nav-link"href="{%url 'login'%}">Cambiar cuenta</a>
            </li>
        </ul>
      </nav>
    

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lobster&family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
</head>
<body>
    <div class="container mt-5">
        {% if messages %}
    {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
{% endif %}
        <h1 class="logo">Best-feed</h1>
        {% if error %}
            <div class="alert alert-danger">{{ error }}</div>
        {% endif %}
        <form method="post">
            {% csrf_token %}
            <input type="text" name="username" class="form-control" placeholder="Nombre de usuario" required>
            <input type="password" name="contraseña" class="form-control" placeholder="Contraseña" required>
            <input type="submit" class="btn btn-success" value="Iniciar sesión">
            <a href="{% url 'register' %}" class="btn btn-secondary ashu">Crear tu cuenta</a>
        </form>
    </div>
</body>
</html>

templates/materiaCrear-bodeguero.html
{%include 'header_bodeguero.html'%}
<div class="container mt-5">
    <div class="alert alert-primary display-1">{{titulo}}</div>
    <form method="POST">
        {% csrf_token %}
       
        <div class="mb-3">
          
          {{ form.nombre.label_tag }}
          
          {{ form.nombre }}  
      </div>
      {% if form.nombre.errors %}
      <div class="text-danger">
          {{ form.nombre.errors.0 }}
      </div>
  {% endif %}
      <div class="mb-3">
          
        {{ form.unidadMedida.label_tag }} 
        {{ form.unidadMedida }}  
    </div>
        <input type="hidden" name="cantidad" value="0">
        <input type="hidden" name="estado" value="True"> 
        <input type="submit" value="Crear">
    </form>
    <div>
      <a href="{%url 'materiaVerBodeguero'%}" class="btn btn-info">Volver</a>
    </div>
</div>
{%include 'footer.html'%}

templates/materiaCrear.html
{%include 'header.html'%}
<div class="container mt-5">
    <div class="alert alert-primary display-1">{{titulo}}</div>
    <form method="POST">
      {% csrf_token %}
      {% if messages %}
      {% for message in messages %}
          <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
              {{ message }}
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
      {% endfor %}
  {% endif %}
     
      <div class="mb-3">
        
        {{ form.nombre.label_tag }}
        
        {{ form.nombre }}  
    </div>
    {% if form.nombre.errors %}
    <div class="text-danger">
        {{ form.nombre.errors.0 }}
    </div>
{% endif %}
    <div class="mb-3">
        
      {{ form.unidadMedida.label_tag }} 
      {{ form.unidadMedida }}  
  </div>
      <input type="hidden" name="cantidad" value="0">
      <input type="hidden" name="estado" value="True"> 
      <button type="submit"class="btn btn-primary">Crear </button>
  </form>
    <div>
      <a href="{%url 'materiaVer'%}" class="btn btn-info">Volver</a>
    </div>
</div>
{%include 'footer.html'%}

templates/materiaDeshabilitadas.html
{%include 'header.html'%}

  <div class="container">
    <div class="alert alert-primary display-1">{{titulo}}</div>
    {% if messages %}
    {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
{% endif %}
    <a href="{%url 'materiaVer'%}" class="btn btn-success">
        <i class="bi bi-plus-circle-fill"></i> Materias Habilitadas
    </a>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Nombre</th>
                    <th>Cantidad</th>
                    <th>Unidad</th>
                    <th>Estado</th>
                    <th colspan="3">Acciones</th>
                </tr>
            </thead>
            <tbody>
                {%for mat in materia%}
                <tr>
                    <td>{{mat.id}}</td>
                    <td>{{mat.nombre}}</td>
                    <td>{{mat.cantidad}}</td>
                    <td>{{mat.unidadMedida}}</td>
                    <td>{{mat.estadoMateria}}</td>
                
                        <td>
                            <a href="{%url 'materiasHabilitar' mat.id%}" class="btn btn-success">
                                Habilitar
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {%include 'footer.html'%}

templates/productosCrear.html
{%include 'header.html'%}

<div class="container mt-5">
    <div class="alert alert-primary display-1">{{titulo}}</div>
    <form method="POST">
      {% csrf_token %}
      {{ form.as_p }}
    
      <h3>Composición</h3>
      {{ formset.management_form }}
      {% for form in formset %}
          <div>
              {{ form.as_p }}
        </div>
    {% endfor %}
        
        <input type="submit" value="Crear">
    </form>
    <div>
      <a href="{%url 'productosVer'%}" class="btn btn-info">Volver</a>
    </div>
</div>
{%include 'footer.html'%}

templates/productosNuevos.html
{% include 'header.html' %}
<div class="container mt-5">

<form method="post">
  {% csrf_token %}
  {% if messages %}
        {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    {% endif %}

  <div class="mb-3">
    {{ form.nombre.label_tag }}
    {{ form.nombre }}
  </div>
  <div class="mb-3">
    {{ form.cantidad.label_tag }}
    {{ form.cantidad }}
  </div>

  <h3>Composición:</h3>
  {% for materia in materias_primas %}
    <div class="mb-3 d-flex align-items-center">
      <div class="form-check me-3">
        <input type="checkbox" id="materia_{{ materia.id }}" name="composicion" value="{{ materia.id }}" class="form-check-input">
        <label for="materia_{{ materia.id }}" class="form-check-label">{{ materia.nombre }}</label>
      </div>
      <label for="cantidad_{{ materia.id }}" class="me-2">Cantidad utilizada</label>
      <input type="number" id="cantidad_{{ materia.id }}" name="cantidad_utilizada_{{ materia.id }}" class="form-control" style="width: 150px;" required>
    </div>
  {% endfor %}

  <button class="btn btn-info" type="submit">Crear Producto</button>
</form>
</div>

{% include 'footer.html' %}

templates/proveedoresDeshabilitar.html
{%include 'header.html'%}
<div class="container">
    <div class="alert alert-primary display-1">{{titulo}}</div>
    {% if messages %}
    {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
{% endif %}
    <a href="{%url 'proveedoresVer'%}" class="btn btn-success">
        <i class="bi bi-plus-circle-fill"></i> Proveedores Habilitados
    </a>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Nombre</th>
                    <th>Contacto</th>
                    <th>Estado</th>
                    <th colspan="3">Acciones</th>
                </tr>
            </thead>
            <tbody>
                {%for pro in proveedores%}
                <tr>
                    <td>{{pro.id}}</td>
                    <td>{{pro.nombre}}</td>
                    <td>{{pro.contacto}}</td>
                    <td>{{pro.estado}}</td>
                
                        <td>
                            <a href="{%url 'proveedoresHabilitar' pro.id%}" class="btn btn-success">
                                Habilitar
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{%include 'footer.html'%}